pagetitle: "The SRQR guidelines for reporting qualitative research studies"
title-prefix: SRQR
id: SRQR
description-meta: "#PLACEHOLDER"
author-meta: "#PLACEHOLDER"
doi: 10.1097/ACM.0000000000000388
translations:
  - language: "French"
    url: "https://www.google.com"
  - language: "German"
    url: "https://www.google.com"
items: 
  - title
  - abstract
  - Introduction: 
    - problem
    - purpose
  - Methods:
    - approach

